M48
; DRILL file {KiCad 9.0.7} date 2026-10-08T00:29:50-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-08T00:29:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X147.96Y-56.96
X147.96Y-59.5
T2
X145.0Y-47.0
X161.0Y-71.0
X189.0Y-47.0
M30
